{% set name = "pytorch-metric-learning" %}
{% set version = "1.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 96dec0eb949f962bef19ec75408b846f513b13c30c1c120d616988911a6a0d4b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - numpy
    - pip
    - python >=3.6
    - scikit-learn
    - pytorch >=1.6.0
    - torchvision
    - tqdm
  run:
    - numpy
    - python >=3.6
    - scikit-learn
    - pytorch >=1.6.0
    - torchvision
    - tqdm

test:
  imports:
    - pytorch_metric_learning
    - pytorch_metric_learning.distances
    - pytorch_metric_learning.losses
    - pytorch_metric_learning.miners
    - pytorch_metric_learning.reducers
    - pytorch_metric_learning.regularizers
    - pytorch_metric_learning.samplers
    - pytorch_metric_learning.testers
    - pytorch_metric_learning.trainers
    - pytorch_metric_learning.utils

about:
  home: "https://github.com/KevinMusgrave/pytorch-metric-learning"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "The easiest way to use deep metric learning in your application. Modular, flexible, and extensible. Written in PyTorch."
  doc_url: "https://kevinmusgrave.github.io/pytorch-metric-learning"
  dev_url: ""

extra:
  recipe-maintainers:
    - KevinMusgrave

